const tvMovie = [
  {
    "adult": false,
    "backdrop_path": "/dW7F0nNVbjFesNKdw950GJ07T4p.jpg",
    "genre_ids": [
      10770,
      16,
      878,
      28,
      12,
      35,
      18,
      14,
      10402
    ],
    "id": 537061,
    "original_language": "en",
    "original_title": "Steven Universe: The Movie",
    "overview": "Two years after bringing peace to the galaxy, Steven Universe sees his past come back to haunt him in the form of a deranged Gem who wants to destroy the Earth.",
    "popularity": 28.433,
    "poster_path": "/8mRgpubxHqnqvENK4Bei30xMDvy.jpg",
    "release_date": "2019-09-02",
    "title": "Steven Universe: The Movie",
    "video": false,
    "vote_average": 8.211,
    "vote_count": 791
  },
  {
    "adult": false,
    "backdrop_path": "/adlZgxAudw3ZPA0HUcDzSTKrH8B.jpg",
    "genre_ids": [
      16,
      10770,
      14,
      28
    ],
    "id": 755812,
    "original_language": "fr",
    "original_title": "Miraculous World : New York, les héros unis",
    "overview": "Teen Parisian superheroes Ladybug and Chat Noir visit New York on a field trip and discover that superheroes exist in the United States too.",
    "popularity": 42.251,
    "poster_path": "/9YbyvcrHmY2SVbdfXpb8mC4Fy0g.jpg",
    "release_date": "2020-12-18",
    "title": "Miraculous World: New York, United HeroeZ",
    "video": false,
    "vote_average": 8.149,
    "vote_count": 1037
  },
  {
    "adult": false,
    "backdrop_path": "/gPW90IPq6Go8hlT0n7Es3cFl7ly.jpg",
    "genre_ids": [
      18,
      10770
    ],
    "id": 550776,
    "original_language": "en",
    "original_title": "Believe Me: The Abduction of Lisa McVey",
    "overview": "On the night she plans on taking her own life, 17-year-old 'Lisa McVey' is kidnapped and finds herself fighting to stay alive and manages to be a victim of rape. She manages to talk her attacker into releasing her, but when she returns home, no one believes her story except for one detective, who suspects she was abducted by a serial killer. Based on horrifying true events.",
    "popularity": 20.975,
    "poster_path": "/qbJEzCzEKDHPZDiRvSSBiYEKaAH.jpg",
    "release_date": "2018-09-30",
    "title": "Believe Me: The Abduction of Lisa McVey",
    "video": false,
    "vote_average": 8.106,
    "vote_count": 567
  },
  {
    "adult": false,
    "backdrop_path": "/pSjGsbqyKUzF8rHzL0vtVWV1pS6.jpg",
    "genre_ids": [
      18,
      36,
      10770
    ],
    "id": 21634,
    "original_language": "en",
    "original_title": "Prayers for Bobby",
    "overview": "Bobby Griffith was his mother's favorite son, the perfect all-American boy growing up under deeply religious influences in Walnut Creek, California. Bobby was also gay. Struggling with a conflict no one knew of, much less understood, Bobby finally came out to his family.",
    "popularity": 13.2,
    "poster_path": "/1viFwXluAettogGDsTrSUUg29lZ.jpg",
    "release_date": "2009-01-24",
    "title": "Prayers for Bobby",
    "video": false,
    "vote_average": 8.1,
    "vote_count": 547
  },
  {
    "adult": false,
    "backdrop_path": "/rlNnwObbMu5G2FaOUlacnUIdIIA.jpg",
    "genre_ids": [
      16,
      14,
      28,
      10770
    ],
    "id": 726684,
    "original_language": "fr",
    "original_title": "Miraculous World : Shanghai, la légende de Ladydragon",
    "overview": "On school break, Marinette heads to Shanghai to meet Adrien. But after arriving, Marinette loses all her stuff, including the Miraculous that allows her to turn into Ladybug!",
    "popularity": 53.79,
    "poster_path": "/qQ0VKsGRQ2ofAmswGNzZnvC1xPE.jpg",
    "release_date": "2021-05-15",
    "title": "Miraculous World: Shanghai – The Legend of Ladydragon",
    "video": false,
    "vote_average": 7.897,
    "vote_count": 601
  },
  {
    "adult": false,
    "backdrop_path": "/gGeoc8rFfPRIakXNttoFU85YVwv.jpg",
    "genre_ids": [
      80,
      18,
      9648,
      10770
    ],
    "id": 379170,
    "original_language": "en",
    "original_title": "Sherlock: The Abominable Bride",
    "overview": "Sherlock Holmes and Dr. Watson find themselves in 1890s London in this holiday special.",
    "popularity": 20.071,
    "poster_path": "/hibE8cyZs2Bm0o4WaWd1pppvjO2.jpg",
    "release_date": "2016-01-01",
    "title": "Sherlock: The Abominable Bride",
    "video": false,
    "vote_average": 7.861,
    "vote_count": 2171
  },
  {
    "adult": false,
    "backdrop_path": "/xHGTnvmrNaDLyysdvqOGKAcaNpQ.jpg",
    "genre_ids": [
      16,
      35,
      878,
      10770,
      12,
      28
    ],
    "id": 354857,
    "original_language": "en",
    "original_title": "Regular Show: The Movie",
    "overview": "After a high school lab experiment goes horribly wrong, Mordecai and Rigby must go back in time to battle an evil volleyball coach in order to save the universe — and their friendship.",
    "popularity": 15.014,
    "poster_path": "/p44RoW4naoE1nlSGOqqT0J2pc09.jpg",
    "release_date": "2015-09-01",
    "title": "Regular Show: The Movie",
    "video": false,
    "vote_average": 7.859,
    "vote_count": 345
  },
  {
    "adult": false,
    "backdrop_path": "/tLoCvK6BHqeGOQ5MzfH8HVFKYoE.jpg",
    "genre_ids": [
      53,
      10770,
      18,
      9648
    ],
    "id": 185789,
    "original_language": "en",
    "original_title": "Mulholland Dr.",
    "overview": "Initially, \"Mulholland Dr.\" was to mark David Lynch's return to television. It is a retooling of a script originally shot as a 94-minute pilot for a TV series (co-written with TV screenwriter Joyce Eliason) for the channel ABC, which had approved the script, but chose not even to air the pilot once it was done in 1999, despite Lynch's labours to cut the project to their liking. It was left in limbo until 18 month later French company Studio Canal Plus (also producer of 'The Straight Story') agreed to pay ABC $7 million for the pilot, and budget a few million more to turn the pilot into a two-hour, 27-minute movie. The cost of the film doubled to $14 million as sets had to be reconstructed and actors recalled.",
    "popularity": 6.653,
    "poster_path": "/oGXtT5UW8lDWt8uxlww2zw9GmBs.jpg",
    "release_date": "1999-01-01",
    "title": "Mulholland Dr.",
    "video": false,
    "vote_average": 7.83,
    "vote_count": 446
  },
  {
    "adult": false,
    "backdrop_path": "/pO1SnM5a1fEsYrFaVZW78Wb0zRJ.jpg",
    "genre_ids": [
      16,
      12,
      10751,
      35,
      10770
    ],
    "id": 677638,
    "original_language": "en",
    "original_title": "We Bare Bears: The Movie",
    "overview": "When Grizz, Panda, and Ice Bear's love of food trucks and viral videos get out of hand, the brothers are now chased away from their home and embark on a trip to Canada, where they can live in peace.",
    "popularity": 30.691,
    "poster_path": "/kPzcvxBwt7kEISB9O4jJEuBn72t.jpg",
    "release_date": "2020-06-30",
    "title": "We Bare Bears: The Movie",
    "video": false,
    "vote_average": 7.813,
    "vote_count": 784
  },
  {
    "adult": false,
    "backdrop_path": "/p0boFm5Z1HzO6LHMBuLYUM48iVV.jpg",
    "genre_ids": [
      10751,
      10770,
      12,
      14
    ],
    "id": 506574,
    "original_language": "en",
    "original_title": "Descendants 3",
    "overview": "The teenagers of Disney's most infamous villains return to the Isle of the Lost to recruit a new batch of villainous offspring to join them at Auradon Prep.",
    "popularity": 57.11,
    "poster_path": "/7IRy0iHdaS0JI3ng4ZYlk5gLSFn.jpg",
    "release_date": "2019-08-02",
    "title": "Descendants 3",
    "video": false,
    "vote_average": 7.735,
    "vote_count": 1397
  },
  {
    "adult": false,
    "backdrop_path": "/fey7NzJ61KAAVPfUgcpaahW5gZ5.jpg",
    "genre_ids": [
      16,
      28,
      878,
      10770
    ],
    "id": 16237,
    "original_language": "en",
    "original_title": "Teen Titans: Trouble in Tokyo",
    "overview": "America's coolest heroes Teen Titans head to Japan as they spring into action when a new threat, the dichromatic ninja Saico-Tek, appears in their city. A chase across the city ensues, ending at Titans Tower. Saico-Tek is interrogated by Robin with the aid of a translation program, and reveals the identity of the one who sent him. The ninja then escapes his bonds and vanishes after destroying a fire sprinkler, and the Titans' only lead is to search for his mysterious master - the shadowy figure known as Brushogun.",
    "popularity": 15.032,
    "poster_path": "/4wMlDE1HzkVyYeDKuY1oDOWQlN2.jpg",
    "release_date": "2006-09-15",
    "title": "Teen Titans: Trouble in Tokyo",
    "video": false,
    "vote_average": 7.71,
    "vote_count": 346
  },
  {
    "adult": false,
    "backdrop_path": "/fvUmnxS9xaUUl0eWygvcA1hPdTV.jpg",
    "genre_ids": [
      80,
      53,
      10770
    ],
    "id": 801335,
    "original_language": "en",
    "original_title": "Girl in the Basement",
    "overview": "Sara is a teen girl who is looking forward to her 18th birthday to move away from her controlling father Don. But before she could even blow out the candles, Don imprisons her in the basement of their home.",
    "popularity": 41.737,
    "poster_path": "/qmddUxRwbsxHa7oEXm4PWh1KZe8.jpg",
    "release_date": "2021-02-27",
    "title": "Girl in the Basement",
    "video": false,
    "vote_average": 7.707,
    "vote_count": 606
  },
  {
    "adult": false,
    "backdrop_path": "/ucWnzjWWWd6CmRal8J3tWz6m1A7.jpg",
    "genre_ids": [
      16,
      10751,
      35,
      10770
    ],
    "id": 13187,
    "original_language": "en",
    "original_title": "A Charlie Brown Christmas",
    "overview": "When Charlie Brown complains about the overwhelming materialism that he sees amongst everyone during the Christmas season, Lucy suggests that he become director of the school Christmas pageant. Charlie Brown accepts, but it is a frustrating struggle. When an attempt to restore the proper spirit with a forlorn little fir Christmas tree fails, he needs Linus' help to learn the meaning of Christmas.",
    "popularity": 22.808,
    "poster_path": "/vtaufTzJBMJAeziQA1eP4BLU24C.jpg",
    "release_date": "1965-12-09",
    "title": "A Charlie Brown Christmas",
    "video": false,
    "vote_average": 7.7,
    "vote_count": 628
  },
  {
    "adult": false,
    "backdrop_path": "/rTf1rucbSn8IaW4AU11lvBk3JmX.jpg",
    "genre_ids": [
      80,
      18,
      10770
    ],
    "id": 12219,
    "original_language": "en",
    "original_title": "12 Angry Men",
    "overview": "During the trial of a man accused of his father's murder, a lone juror takes a stand against the guilty verdict handed down by the others as a result of their preconceptions and prejudices.",
    "popularity": 18.844,
    "poster_path": "/whDdYx3lh1LHTN0VlPFt51fX29g.jpg",
    "release_date": "1997-08-17",
    "title": "12 Angry Men",
    "video": false,
    "vote_average": 7.7,
    "vote_count": 304
  },
  {
    "adult": false,
    "backdrop_path": "/96SADhPnkXnVN3KaRKsDeBovLcm.jpg",
    "genre_ids": [
      28,
      14,
      10770
    ],
    "id": 877703,
    "original_language": "en",
    "original_title": "Teen Wolf: The Movie",
    "overview": "The wolves are howling once again, as a terrifying ancient evil emerges in Beacon Hills. Scott McCall, no longer a teenager yet still an Alpha, must gather new allies and reunite trusted friends to fight back against this powerful and deadly enemy.",
    "popularity": 58.377,
    "poster_path": "/wAkpPm3wcHRqZl8XjUI3Y2chYq2.jpg",
    "release_date": "2023-01-18",
    "title": "Teen Wolf: The Movie",
    "video": false,
    "vote_average": 7.59,
    "vote_count": 712
  },
  {
    "adult": false,
    "backdrop_path": "/5i9G9oQdnshtpgJpa7HEGdvjza7.jpg",
    "genre_ids": [
      14,
      10749,
      10770
    ],
    "id": 599521,
    "original_language": "en",
    "original_title": "Z-O-M-B-I-E-S 2",
    "overview": "Zed and Addison are back at Seabrook High, where, after a groundbreaking semester, they continue to steer both their school and community toward unity. But the arrival of a new group of outsiders – mysterious werewolves – threatens to shake up the newfound peace and causes a rift in Zed and Addison’s budding romance.",
    "popularity": 27.939,
    "poster_path": "/frTwEqSMWQ27oQeuiBO5PT0ZNqq.jpg",
    "release_date": "2020-06-13",
    "title": "Z-O-M-B-I-E-S 2",
    "video": false,
    "vote_average": 7.6,
    "vote_count": 417
  },
  {
    "adult": false,
    "backdrop_path": "/vtml6FFkXCEG7j30dkNsK5F7SdK.jpg",
    "genre_ids": [
      10751,
      16,
      10770,
      35
    ],
    "id": 13353,
    "original_language": "en",
    "original_title": "It's the Great Pumpkin, Charlie Brown",
    "overview": "This classic \"Peanuts\" tale focuses on the thumb-sucking, blanket-holding Linus, and his touching faith in the \"Great Pumpkin.\" When Linus discovers that no one else believes in the creature, he sets out to prove that the Pumpkin's no myth—by spending the night alone in a pumpkin patch.",
    "popularity": 15.011,
    "poster_path": "/59wp9OWexYsxlSPHYmVLsl5xlFt.jpg",
    "release_date": "1966-10-27",
    "title": "It's the Great Pumpkin, Charlie Brown",
    "video": false,
    "vote_average": 7.479,
    "vote_count": 361
  },
  {
    "adult": false,
    "backdrop_path": "/MNyDL2YlOckMcOcdYna2N1UCxE.jpg",
    "genre_ids": [
      16,
      35,
      10770
    ],
    "id": 874300,
    "original_language": "en",
    "original_title": "South Park: Post COVID: The Return of COVID",
    "overview": "If Stan, Kyle and Cartman could just work together, they could go back in time to make sure Covid never happened. But traveling back to the past seems to be the easy answer until they meet Victor Chaos.",
    "popularity": 15.939,
    "poster_path": "/xD88mrJ8hsqYVqQ6kinNNGQLdg1.jpg",
    "release_date": "2021-12-16",
    "title": "South Park: Post COVID: The Return of COVID",
    "video": false,
    "vote_average": 7.471,
    "vote_count": 361
  },
  {
    "adult": false,
    "backdrop_path": "/wNQpfAZkySbinb93qVwWIWaot1x.jpg",
    "genre_ids": [
      10402,
      14,
      35,
      878,
      10751,
      10770
    ],
    "id": 809107,
    "original_language": "en",
    "original_title": "Z-O-M-B-I-E-S 3",
    "overview": "Zed and Addison are beginning their final year at Seabrook High in the town that’s become a safe haven for monsters and humans alike. Zed is anticipating an athletic scholarship that will make him the first Zombie to attend college, while Addison is gearing up for Seabrook’s first international cheer-off competition. Then suddenly, extraterrestrial beings appear around Seabrook, provoking something other than friendly competition.",
    "popularity": 33.26,
    "poster_path": "/2QxbpQgzmTQjezu9YOeBk8JFzKg.jpg",
    "release_date": "2022-07-09",
    "title": "Z-O-M-B-I-E-S 3",
    "video": false,
    "vote_average": 7.451,
    "vote_count": 347
  },
  {
    "adult": false,
    "backdrop_path": "/lBy0tIjlc3rAy4dih74RFDIpxoP.jpg",
    "genre_ids": [
      18,
      35,
      10770
    ],
    "id": 65218,
    "original_language": "en",
    "original_title": "Lemonade Mouth",
    "overview": "When five ragtag freshman first meet in detention, it seems they have nothing in common. But, through music, they form an unbreakable bond and discover they have the makings of the greatest high school garage band in history! In the face of incredible odds, Olivia, Stella, Wen, Mohini and Charlie find they can make a real difference when they learn to lean on each other and let go of everything holding back their dreams.",
    "popularity": 14.441,
    "poster_path": "/5Tbbxf38c16kbfezmXkPYS2tYRN.jpg",
    "release_date": "2011-04-15",
    "title": "Lemonade Mouth",
    "video": false,
    "vote_average": 7.44,
    "vote_count": 1010
  },
  {
    "adult": false,
    "backdrop_path": "/nVl6SKKzuweWqDo56Iipov2tqm0.jpg",
    "genre_ids": [
      28,
      53,
      10770
    ],
    "id": 839,
    "original_language": "en",
    "original_title": "Duel",
    "overview": "Traveling businessman David Mann angers the driver of a rusty tanker while crossing the California desert. A simple trip turns deadly, as Mann struggles to stay on the road while the tanker plays cat and mouse with his life.",
    "popularity": 21.089,
    "poster_path": "/w9Vk1Txx14vWvACELFYFlixrsfr.jpg",
    "release_date": "1971-11-13",
    "title": "Duel",
    "video": false,
    "vote_average": 7.425,
    "vote_count": 1710
  },
  {
    "adult": false,
    "backdrop_path": "/7ArGqBWnPD3EWiwwteBzIbHOO7E.jpg",
    "genre_ids": [
      16,
      35,
      878,
      10770
    ],
    "id": 7249,
    "original_language": "en",
    "original_title": "Futurama: Bender's Big Score",
    "overview": "The Planet Express crew return from cancellation, only to be robbed blind by hideous \"sprunging\" scam artists.  Things go from bad to worse when the scammers hack Bender, start traveling through time, and take Earth over entirely!  Will the crew be able to save the day, or will Bender's larcenous tendencies and their general incompetence doom them all?",
    "popularity": 12.451,
    "poster_path": "/bmVE90IHvx4uXQgtbRtu4RyMWpt.jpg",
    "release_date": "2007-11-27",
    "title": "Futurama: Bender's Big Score",
    "video": false,
    "vote_average": 7.415,
    "vote_count": 632
  },
  {
    "adult": false,
    "backdrop_path": "/1WQ4bHXzS7DpGppkS2PcpFvpY7T.jpg",
    "genre_ids": [
      18,
      14,
      10770,
      10751
    ],
    "id": 13189,
    "original_language": "en",
    "original_title": "A Christmas Carol",
    "overview": "Miser Ebenezer Scrooge is awakened on Christmas Eve by spirits who reveal to him his own miserable existence, what opportunities he wasted in his youth, his current cruelties, and the dire fate that awaits him if he does not change his ways. Scrooge is faced with his own story of growing bitterness and meanness, and must decide what his own future will hold: death or redemption.",
    "popularity": 18.931,
    "poster_path": "/kGmpIkjVRWHQ97AiEXC0pLt5VtY.jpg",
    "release_date": "1984-10-09",
    "title": "A Christmas Carol",
    "video": false,
    "vote_average": 7.4,
    "vote_count": 332
  },
  {
    "adult": false,
    "backdrop_path": "/mLihPIodzSenkZtiUauDy4e9hRs.jpg",
    "genre_ids": [
      10751,
      10402,
      14,
      10770,
      12,
      28,
      10749
    ],
    "id": 417320,
    "original_language": "en",
    "original_title": "Descendants 2",
    "overview": "When the pressure to be royal becomes too much for Mal, she returns to the Isle of the Lost where her archenemy Uma, Ursula's daughter, has taken her spot as self-proclaimed queen.",
    "popularity": 39.428,
    "poster_path": "/qoNlGfQmFZ37Gf5fRBaCTLlOZtx.jpg",
    "release_date": "2017-07-21",
    "title": "Descendants 2",
    "video": false,
    "vote_average": 7.366,
    "vote_count": 1533
  },
  {
    "adult": false,
    "backdrop_path": "/zd3p7GKopxH4rIjGoDQ1ugalUtx.jpg",
    "genre_ids": [
      16,
      10751,
      10770
    ],
    "id": 13382,
    "original_language": "en",
    "original_title": "Rudolph the Red-Nosed Reindeer",
    "overview": "Sam the snowman tells us the story of a young red-nosed reindeer who, after being ousted from the reindeer games because of his glowing nose, teams up with Hermey, an elf who wants to be a dentist, and Yukon Cornelius, the prospector. They run into the Abominable Snowman and find a whole island of misfit toys. Rudoph vows to see if he can get Santa to help the toys, and he goes back to the North Pole on Christmas Eve. But Santa's sleigh is fogged in. But when Santa looks over Rudolph, he gets a very bright idea...",
    "popularity": 33.721,
    "poster_path": "/xjAElUhXuc7zFJPj3qUHjcySNsE.jpg",
    "release_date": "1964-12-06",
    "title": "Rudolph the Red-Nosed Reindeer",
    "video": false,
    "vote_average": 7.366,
    "vote_count": 532
  },
  {
    "adult": false,
    "backdrop_path": "/wkGVEq3flo1Tz86FPnsC9yNHFOX.jpg",
    "genre_ids": [
      10749,
      18,
      10402,
      10770
    ],
    "id": 440596,
    "original_language": "en",
    "original_title": "Kiss and Cry",
    "overview": "A romantic drama based on the story of Carley Allison, a promising 18 year old figure skater and singer who made medical history in her fight against a rare 1 in 3.5 billion type of sarcoma.",
    "popularity": 10.421,
    "poster_path": "/uHErYJ2TfP0ihIEMpD2zCvbVIIB.jpg",
    "release_date": "2017-02-10",
    "title": "Kiss and Cry",
    "video": false,
    "vote_average": 7.3,
    "vote_count": 403
  },
  {
    "adult": false,
    "backdrop_path": "/8eVxRHRegqbFL2ugnJlvOGIarX1.jpg",
    "genre_ids": [
      36,
      18,
      10752,
      10770
    ],
    "id": 12900,
    "original_language": "en",
    "original_title": "Conspiracy",
    "overview": "The historical recreation of the 1942 Wannsee Conference, in which Nazi and SS leaders gathered in a Berlin suburb to discuss the \"Final Solution to the Jewish Question\". Led by SS-General Reinhard Heydrich, this group of high ranking German officials came to the historic and far reaching decision that the Jews of Europe were to be exterminated in what would come to be known as the Holocaust.",
    "popularity": 14.315,
    "poster_path": "/Onqn8XXyhANuy1LIL7AIN6unQk.jpg",
    "release_date": "2001-05-19",
    "title": "Conspiracy",
    "video": false,
    "vote_average": 7.3,
    "vote_count": 360
  },
  {
    "adult": false,
    "backdrop_path": "/66T5HymEPBtrwJHehEUlPjB2dec.jpg",
    "genre_ids": [
      10770,
      35,
      10751
    ],
    "id": 360606,
    "original_language": "en",
    "original_title": "Adventures in Babysitting",
    "overview": "Two teen rival babysitters, Jenny and Lola, team up to hunt down one of their kids who accidentally ran away into the big city without any supervision.",
    "popularity": 17.177,
    "poster_path": "/xuCPo0krpAcK2s1uMCZs93turdk.jpg",
    "release_date": "2016-06-24",
    "title": "Adventures in Babysitting",
    "video": false,
    "vote_average": 7.299,
    "vote_count": 388
  },
  {
    "adult": false,
    "backdrop_path": "/lkeBhXGJFRlhI7cBWn8LQQAdZqK.jpg",
    "genre_ids": [
      10751,
      16,
      878,
      35,
      10770
    ],
    "id": 594328,
    "original_language": "en",
    "original_title": "Phineas and Ferb The Movie: Candace Against the Universe",
    "overview": "Phineas and Ferb travel across the galaxy to rescue their older sister Candace, who has been abducted by aliens and taken to a utopia in a far-off planet, free of her pesky little brothers.",
    "popularity": 26.12,
    "poster_path": "/n6hptKS7Y0ZjkYwbqKOK3jz9XAC.jpg",
    "release_date": "2020-08-28",
    "title": "Phineas and Ferb The Movie: Candace Against the Universe",
    "video": false,
    "vote_average": 7.288,
    "vote_count": 349
  },
  {
    "adult": false,
    "backdrop_path": "/d7i2jAAbQLfLRsatyPoBsbu8W3Q.jpg",
    "genre_ids": [
      10402,
      14,
      35,
      10749,
      27,
      10770
    ],
    "id": 483980,
    "original_language": "en",
    "original_title": "Z-O-M-B-I-E-S",
    "overview": "Two star-crossed freshmen – a zombie, Zed and a cheerleader, Addison – each outsiders in their unique ways, befriend each other and work together to show their high school and the Seabrook community what they can achieve when they embrace their differences.",
    "popularity": 22.997,
    "poster_path": "/6S9O5U7Ietqh6zTtZhGbhbA3Pze.jpg",
    "release_date": "2018-02-16",
    "title": "Z-O-M-B-I-E-S",
    "video": false,
    "vote_average": 7.288,
    "vote_count": 639
  },
  {
    "adult": false,
    "backdrop_path": "/4Dk6TvdpjEPyPBElFdLlLJu1rju.jpg",
    "genre_ids": [
      18,
      80,
      10770
    ],
    "id": 336845,
    "original_language": "en",
    "original_title": "Cleveland Abduction",
    "overview": "A single mother becomes Ariel Castro's first kidnapping victim, and finds herself trapped in his home with two other women for 11 years.",
    "popularity": 17.426,
    "poster_path": "/xSfHS7KnZWJrMf6l54UU7yKAsAI.jpg",
    "release_date": "2015-05-02",
    "title": "Cleveland Abduction",
    "video": false,
    "vote_average": 7.2,
    "vote_count": 329
  },
  {
    "adult": false,
    "backdrop_path": "/iraunnwrss2DJy4xayyntWHaAZR.jpg",
    "genre_ids": [
      18,
      10770
    ],
    "id": 56831,
    "original_language": "en",
    "original_title": "The Sunset Limited",
    "overview": "A deeply religious black ex-con thwarts the suicide attempt of an asocial white college professor who tries to throw himself in front of an oncoming subway train, 'The Sunset Limited.' As the one attempts to connect on a rational, spiritual and emotional level, the other remains steadfast in his hard-earned despair. Locked in a philosophical debate, both passionately defend their personal credos and try to convert the other.",
    "popularity": 9.717,
    "poster_path": "/8cwqylJVbCfMflcjXQ71CwsXdpf.jpg",
    "release_date": "2011-02-12",
    "title": "The Sunset Limited",
    "video": false,
    "vote_average": 7.188,
    "vote_count": 401
  },
  {
    "adult": false,
    "backdrop_path": "/hPHahVM3JDlE0Zexu6avavypk0g.jpg",
    "genre_ids": [
      28,
      12,
      878,
      10770
    ],
    "id": 13001,
    "original_language": "en",
    "original_title": "Stargate: The Ark of Truth",
    "overview": "SG-1 searches for an ancient weapon which could help them defeat the Ori, and discover it may be in the Ori's own home galaxy. As the Ori prepare to send ships through to the Milky Way to attack Earth, SG-1 travels to the Ori galaxy aboard the Odyssey. The International Oversight committee have their own plans and SG-1 finds themselves in a distant galaxy fighting two powerful enemies.",
    "popularity": 17.164,
    "poster_path": "/kIqsCdZBmKYuPwaDnrFYzK1gqlM.jpg",
    "release_date": "2008-03-11",
    "title": "Stargate: The Ark of Truth",
    "video": false,
    "vote_average": 7.114,
    "vote_count": 447
  },
  {
    "adult": false,
    "backdrop_path": "/wy3ItrIw4DmLFxvFK5LM6FPwdQw.jpg",
    "genre_ids": [
      10751,
      10402,
      12,
      35,
      14,
      10770
    ],
    "id": 277217,
    "original_language": "en",
    "original_title": "Descendants",
    "overview": "A present-day idyllic kingdom where the benevolent teenage son of King Adam and Queen Belle offers a chance of redemption for the troublemaking offspring of Disney's classic villains: Cruella De Vil (Carlos), Maleficent (Mal), the Evil Queen (Evie) and Jafar (Jay).",
    "popularity": 52.127,
    "poster_path": "/65DkgHPSLVjgr6IYkpY9Aqqqid5.jpg",
    "release_date": "2015-07-31",
    "title": "Descendants",
    "video": false,
    "vote_average": 7.112,
    "vote_count": 2192
  },
  {
    "adult": false,
    "backdrop_path": "/rydHABgY7Cj5nZT5Z0zuzUBdPGT.jpg",
    "genre_ids": [
      10770,
      10749,
      18
    ],
    "id": 188538,
    "original_language": "en",
    "original_title": "Remember Sunday",
    "overview": "A lonely, down-on-her-luck waitress meets a handsome, quirky jewelry store clerk and thinks that maybe, finally, she's met Mr. Right. The more Molly gets to know Gus, the more she's intrigued by him. But she's also mystified. Gus is absent-minded, preoccupied. Is he hiding something? The short answer is: yes. He's reluctant to share with her that since suffering a brain aneurysm, he's totally lost his short-term memory. Every day is a brand new day, his life starts anew. Every day he sees Molly he struggles to remember who she is and what she represents. Every day, he has to fall in love with her all over again.",
    "popularity": 9.471,
    "poster_path": "/triS1L9nHDjVwWmYNBItgDo525P.jpg",
    "release_date": "2013-04-21",
    "title": "Remember Sunday",
    "video": false,
    "vote_average": 7.101,
    "vote_count": 481
  },
  {
    "adult": false,
    "backdrop_path": "/aaSYQOoIlDAeCzsKYB47qe2l4Oe.jpg",
    "genre_ids": [
      18,
      10770
    ],
    "id": 36950,
    "original_language": "en",
    "original_title": "You Don't Know Jack",
    "overview": "Controversy and legal problems follow Dr. Jack Kevorkian as he advocates assisted suicide.",
    "popularity": 10.691,
    "poster_path": "/xl4x8aILt9v91TUOKXHIVDZwkXy.jpg",
    "release_date": "2010-04-14",
    "title": "You Don't Know Jack",
    "video": false,
    "vote_average": 7.089,
    "vote_count": 359
  },
  {
    "adult": false,
    "backdrop_path": "/pdhwL4wePKQduRDCDWBPFfpIUH1.jpg",
    "genre_ids": [
      878,
      28,
      18,
      53,
      10770
    ],
    "id": 69315,
    "original_language": "en",
    "original_title": "Battlestar Galactica: Razor",
    "overview": "A two-hour Battlestar Galactica special that tells the story of the Battlestar Pegasus several months prior to it finding the Galactica.",
    "popularity": 11.002,
    "poster_path": "/tO3EoFJj0FJjKelDW5SUtquDIy2.jpg",
    "release_date": "2007-11-12",
    "title": "Battlestar Galactica: Razor",
    "video": false,
    "vote_average": 7.086,
    "vote_count": 366
  },
  {
    "adult": false,
    "backdrop_path": "/cXBWShG3jPpKWJEgadsb1795KXm.jpg",
    "genre_ids": [
      28,
      12,
      878,
      10770
    ],
    "id": 12914,
    "original_language": "en",
    "original_title": "Stargate: Continuum",
    "overview": "Ba'al travels back in time and prevents the Stargate program from being started. SG-1 must somehow restore history.",
    "popularity": 20.038,
    "poster_path": "/aP22JTw7or68WwqwFu1Bwrg66Ev.jpg",
    "release_date": "2008-07-29",
    "title": "Stargate: Continuum",
    "video": false,
    "vote_average": 7.076,
    "vote_count": 462
  },
  {
    "adult": false,
    "backdrop_path": "/ocyOdgL8pGS5KRpRfS69SsS2GMa.jpg",
    "genre_ids": [
      35,
      10751,
      10770,
      10749,
      18
    ],
    "id": 79113,
    "original_language": "en",
    "original_title": "A Princess for Christmas",
    "overview": "After her sister and brother-in-law's tragic deaths, an American woman who is the guardian for her young niece and nephew is invited to a royal European castle for Christmas by her late brother-in-law's father, the Duke of Castlebury. Feeling out of place as a commoner, she is determined to give her family a merry Christmas and surprises herself when she falls for a handsome prince.",
    "popularity": 17.039,
    "poster_path": "/8B0GaAebFRWek6tGSqWAeyJOIp6.jpg",
    "release_date": "2011-12-03",
    "title": "A Princess for Christmas",
    "video": false,
    "vote_average": 7,
    "vote_count": 385
  },
  {
    "adult": false,
    "backdrop_path": "/xe4IIhJ0r3QjrKNPNEjVu3UtcZh.jpg",
    "genre_ids": [
      16,
      35,
      878,
      10770
    ],
    "id": 15060,
    "original_language": "en",
    "original_title": "Futurama: Into the Wild Green Yonder",
    "overview": "Leela becomes an outlaw when she and a group of ecologically-minded feminists attempt to save an asteroid of primitive life forms and the Violet Dwarf star from being destroyed, while Fry joins a secret society and attempts to stop a mysterious species known as the \"Dark Ones\" from destroying all life in the universe.",
    "popularity": 16.672,
    "poster_path": "/oL6SymcxQE6TN9KrrbdyhlulnEG.jpg",
    "release_date": "2009-02-23",
    "title": "Futurama: Into the Wild Green Yonder",
    "video": false,
    "vote_average": 7.027,
    "vote_count": 498
  },
  {
    "adult": false,
    "backdrop_path": "/qXxENmYYPSs4TnPjU8gfnhUo714.jpg",
    "genre_ids": [
      16,
      35,
      10751,
      10770,
      12,
      878
    ],
    "id": 71689,
    "original_language": "en",
    "original_title": "Phineas and Ferb The Movie: Across the 2nd Dimension",
    "overview": "Phineas and Ferb get trapped in an alternate dimension where the evil Doofenshmirtz rules the tri-state area. They must find a way back home with the help of their pet platypus named Perry, who they discover is a secret agent.",
    "popularity": 31.917,
    "poster_path": "/updMFSOZwEftfkJRpozwBlRlYI2.jpg",
    "release_date": "2011-08-05",
    "title": "Phineas and Ferb The Movie: Across the 2nd Dimension",
    "video": false,
    "vote_average": 7.023,
    "vote_count": 504
  },
  {
    "adult": false,
    "backdrop_path": "/nsWgxQrDcTVhSGzAu5kVlw64XB1.jpg",
    "genre_ids": [
      10749,
      35,
      10770,
      10402
    ],
    "id": 35558,
    "original_language": "en",
    "original_title": "Starstruck",
    "overview": "Pop star Christopher Wilde has fame, fortune and a big-budget Hollywood movie awaiting him. But after meeting Jessica Olson, a down-to-earth girl from the Midwest, he is faced with following his heart or doing what's best for his career.",
    "popularity": 15.106,
    "poster_path": "/kuyJuNiiZvu5iNr8Dgv5y75v1uc.jpg",
    "release_date": "2010-02-14",
    "title": "Starstruck",
    "video": false,
    "vote_average": 7.009,
    "vote_count": 1145
  },
  {
    "adult": false,
    "backdrop_path": "/vpviitHyakuHAGlVJOR3fvzN0YP.jpg",
    "genre_ids": [
      16,
      35,
      878,
      10770
    ],
    "id": 12889,
    "original_language": "en",
    "original_title": "Futurama: The Beast with a Billion Backs",
    "overview": "Fresh off ripping space-time a new one at the end of \"Bender's Big Score,\" the Planet Express crew is back to mend the tear in reality, or (hopefully) at least not make it worse.  Beyond the tear, though, lurks a being of inconceivable...tentacularity.  What will become of Earth, and indeed, our universe, when faced with the Beast with a Billion Backs?",
    "popularity": 12.422,
    "poster_path": "/2BW6JAW4wo7t5wD3WVfoijzosvt.jpg",
    "release_date": "2008-06-30",
    "title": "Futurama: The Beast with a Billion Backs",
    "video": false,
    "vote_average": 6.976,
    "vote_count": 513
  },
  {
    "adult": false,
    "backdrop_path": "/aGSjVo8Z0OormalcqRLYnhTZ8WX.jpg",
    "genre_ids": [
      10751,
      16,
      10770
    ],
    "id": 13675,
    "original_language": "en",
    "original_title": "Frosty the Snowman",
    "overview": "A discarded silk top-hat becomes the focus of a struggle between a washed-up stage magician and a group of schoolchildren, after it magically brings a snowman to life. Realizing that newly-living Frosty will melt in spring unless he takes refuge in a colder climate, Frosty and Karen, a young girl who he befriends, stow away on a freight train headed for the north pole. Little do they know that the magician is following them, and he wants his hat back!",
    "popularity": 15.918,
    "poster_path": "/gw7ie4W3iW8nefnZ4kuw8dgYNM2.jpg",
    "release_date": "1969-12-07",
    "title": "Frosty the Snowman",
    "video": false,
    "vote_average": 6.95,
    "vote_count": 307
  },
  {
    "adult": false,
    "backdrop_path": "/5qEbMgADycx8uk3Lyb6ybgozniN.jpg",
    "genre_ids": [
      16,
      10751,
      10770,
      35,
      14
    ],
    "id": 50393,
    "original_language": "en",
    "original_title": "Kung Fu Panda Holiday",
    "overview": "The Winter Feast is Po's favorite holiday. Every year he and his father hang decorations, cook together, and serve noodle soup to the villagers. But this year Shifu informs Po that as Dragon Warrior, it is his duty to host the formal Winter Feast at the Jade Palace. Po is caught between his obligations as the Dragon Warrior and his family traditions: between Shifu and Mr. Ping.",
    "popularity": 25.899,
    "poster_path": "/vJv3pI8pyS13rLjy0ok7a3BiE0a.jpg",
    "release_date": "2010-11-26",
    "title": "Kung Fu Panda Holiday",
    "video": false,
    "vote_average": 6.9,
    "vote_count": 305
  },
  {
    "adult": false,
    "backdrop_path": "/4MWvTT1LlADLcOr2fMpEZrejoKp.jpg",
    "genre_ids": [
      12,
      35,
      10751,
      14,
      10770,
      27
    ],
    "id": 63700,
    "original_language": "en",
    "original_title": "My Babysitter's a Vampire",
    "overview": "Geeky 14-year old Ethan is left to babysit his younger sister, Jane, with his best friend Benny but after Ethan inadvertently puts Jane in harm's way, his parents hire a professional babysitter, the beautiful yet mysterious 17-year-old Sarah who, unbeknownst to them, is actually a fledgling vampire.",
    "popularity": 11.127,
    "poster_path": "/gDnn0tBmuFPRiSwvBl6GBqiHAZz.jpg",
    "release_date": "2010-10-09",
    "title": "My Babysitter's a Vampire",
    "video": false,
    "vote_average": 6.931,
    "vote_count": 369
  },
  {
    "adult": false,
    "backdrop_path": "/zYARGakIhHUvPuVJzlbqU40FrnV.jpg",
    "genre_ids": [
      28,
      12,
      16,
      14,
      878,
      10770
    ],
    "id": 17445,
    "original_language": "en",
    "original_title": "Green Lantern: First Flight",
    "overview": "Test pilot Hal Jordan finds himself recruited as the newest member of the intergalactic police force, The Green Lantern Corps.",
    "popularity": 18.238,
    "poster_path": "/zma3rOg6yJxgJ1Lo9uuw3tJOjbZ.jpg",
    "release_date": "2009-07-28",
    "title": "Green Lantern: First Flight",
    "video": false,
    "vote_average": 6.93,
    "vote_count": 409
  },
  {
    "adult": false,
    "backdrop_path": "/rjK7Fri42mn77bOnN3355XHC7eq.jpg",
    "genre_ids": [
      16,
      35,
      878,
      10770
    ],
    "id": 13253,
    "original_language": "en",
    "original_title": "Futurama: Bender's Game",
    "overview": "When Leela is insulted by a group of space-rednecks (like regular rednecks, but in space) she enters the Planet Express ship in a demolition derby.  She emerges victorious, but when she brings the damaged ship home and the Professor sees the fuel gauge, he's enraged by the hit he's going to take at the Dark Matter pump.  Now the crew have to find a way to break Mom's stranglehold on starship fuel, even if they have to wade through a Lord of the Rings-inspired fantasy-land to do it!",
    "popularity": 10.054,
    "poster_path": "/bx8OVOBn5WP9TJJuOpRzyMCdzzb.jpg",
    "release_date": "2008-11-03",
    "title": "Futurama: Bender's Game",
    "video": false,
    "vote_average": 6.916,
    "vote_count": 499
  },
  {
    "adult": false,
    "backdrop_path": "/gBw3sXDSCqTYi3ppBGtabXziTBS.jpg",
    "genre_ids": [
      10751,
      35,
      10770,
      14
    ],
    "id": 178682,
    "original_language": "en",
    "original_title": "The Wizards Return: Alex vs. Alex",
    "overview": "While visiting Italy with her family, a young wizard accidentally creates an evil version of herself.",
    "popularity": 13.997,
    "poster_path": "/iWL88DymJrzO6hYI1ykUeUohqef.jpg",
    "release_date": "2013-06-01",
    "title": "The Wizards Return: Alex vs. Alex",
    "video": false,
    "vote_average": 6.903,
    "vote_count": 693
  },
  {
    "adult": false,
    "backdrop_path": "/znjVe07uk6VLIMK9Lsd2kGsq97B.jpg",
    "genre_ids": [
      10751,
      10402,
      10770,
      35
    ],
    "id": 177888,
    "original_language": "en",
    "original_title": "Teen Beach Movie",
    "overview": "Life's a beach for surfers Brady and McKenzie – until a rogue wave magically transports them inside the classic '60s beach party flick, \"Wet Side Story,\" where a full-blown rivalry between bikers and surfers threatens to erupt. There, amidst a sea of surfing, singing and dancing, Brady and Mack accidentally change the storyline, and the film’s dreamy hero and heroine fall for them instead of for each other!",
    "popularity": 15.934,
    "poster_path": "/ywX8INXLshhf94pyxc8wE2MO4aT.jpg",
    "release_date": "2013-08-07",
    "title": "Teen Beach Movie",
    "video": false,
    "vote_average": 6.894,
    "vote_count": 885
  },
  {
    "adult": false,
    "backdrop_path": "/vkr2KGu10vCHbK1SM5q2AtWA4TM.jpg",
    "genre_ids": [
      10751,
      28,
      18,
      10749,
      10770
    ],
    "id": 245473,
    "original_language": "en",
    "original_title": "Cloud 9",
    "overview": "Set high atop snow-capped mountains in the adrenaline-fueled world of competitive snowboarding, the Disney Channel Original Movie “Cloud 9″ tells the inspiring story of two snowboarders who must overcome self-doubt to learn that achieving their dreams is possible.",
    "popularity": 21.897,
    "poster_path": "/ztrYqCPwFult7UMTiHyVxp1xHSc.jpg",
    "release_date": "2014-01-17",
    "title": "Cloud 9",
    "video": false,
    "vote_average": 6.884,
    "vote_count": 512
  },
  {
    "adult": false,
    "backdrop_path": "/AfMAcS5HmPPRtJ3d9tipXTQV2Xt.jpg",
    "genre_ids": [
      12,
      10751,
      14,
      10770
    ],
    "id": 34205,
    "original_language": "en",
    "original_title": "Halloweentown II: Kalabar's Revenge",
    "overview": "The Cromwell clan lives in the real world, except for their grandmother who lives in Halloweentown, a place where monsters go to escape reality. But now the son of the Cromwells' old enemy Kalabar has a plan to use the grandmother's book to turn Halloweentown into a grey dreary version of the real world while transforming the denizens of the real world into monsters.",
    "popularity": 12.16,
    "poster_path": "/uDnp52aGXxnfU4vqnnc6YpfzjHb.jpg",
    "release_date": "2001-10-12",
    "title": "Halloweentown II: Kalabar's Revenge",
    "video": false,
    "vote_average": 6.842,
    "vote_count": 304
  },
  {
    "adult": false,
    "backdrop_path": "/dOaF7zNAHYsSaAp8PXrUt4qfm8k.jpg",
    "genre_ids": [
      12,
      35,
      10751,
      14,
      10770
    ],
    "id": 27850,
    "original_language": "en",
    "original_title": "Halloweentown",
    "overview": "On her 13th birthday, Marnie learns she's a witch, discovers a secret portal, and is transported to Halloweentown — a magical place where ghosts and ghouls, witches and werewolves live apart from the human world. But she soon finds herself battling wicked warlocks, evil curses, and endless surprises.",
    "popularity": 14.565,
    "poster_path": "/axYFa20HjBhYFrSz5LHbWuATjGU.jpg",
    "release_date": "1998-11-10",
    "title": "Halloweentown",
    "video": false,
    "vote_average": 6.842,
    "vote_count": 491
  },
  {
    "adult": false,
    "backdrop_path": "/bAHwlrxTvC37wU86kl4D2QJkMfj.jpg",
    "genre_ids": [
      12,
      16,
      35,
      10751,
      14,
      10770
    ],
    "id": 438747,
    "original_language": "en",
    "original_title": "Tangled: Before Ever After",
    "overview": "Rapunzel grapples with the responsibilities of being a princess and the overprotective ways of her father. While she wholeheartedly loves Eugene, Rapunzel does not share his immediate desire to get married and settle down within the castle walls. Determined to live life on her own terms, she and her tough-as-nails Lady-in-Waiting Cassandra embark on a secret adventure where they encounter mystical rocks that magically cause Rapunzel's long blonde hair to grow back. Impossible to break and difficult to hide, Rapunzel must learn to embrace her hair and all that it represents.",
    "popularity": 24.913,
    "poster_path": "/zj82L9maBSW6CAVZltBoFBSuTk1.jpg",
    "release_date": "2017-03-10",
    "title": "Tangled: Before Ever After",
    "video": false,
    "vote_average": 6.8,
    "vote_count": 354
  },
  {
    "adult": false,
    "backdrop_path": "/kIXJRoqUdqU9AowvS7PqBqMK8N8.jpg",
    "genre_ids": [
      10770,
      37,
      18
    ],
    "id": 538225,
    "original_language": "en",
    "original_title": "Deadwood: The Movie",
    "overview": "Follow the 10-year reunion of the Deadwood camp to celebrate South Dakota's statehood. Former rivalries are reignited, alliances are tested and old wounds are reopened, as all are left to navigate the inevitable changes that modernity and time have wrought.",
    "popularity": 13.143,
    "poster_path": "/fCQ13cqd02dop7Chkov0fPl4r3t.jpg",
    "release_date": "2019-06-01",
    "title": "Deadwood: The Movie",
    "video": false,
    "vote_average": 6.781,
    "vote_count": 345
  },
  {
    "adult": false,
    "backdrop_path": "/siidi1AD6JNwWqrepY5DhqCCuEX.jpg",
    "genre_ids": [
      18,
      10751,
      14,
      10770
    ],
    "id": 46169,
    "original_language": "en",
    "original_title": "Twitches Too",
    "overview": "Reunited witch twins Camryn and Alex adjust to their new life as supernatural beings while at the same time trying to maintain a normal existence in this sequel to the magical Disney Channel original movie Twitches. But they soon find themselves going head to head with the forces of darkness that threaten to destroy their world. Luckily, their birth mother, the powerful Miranda, is on hand to help out.",
    "popularity": 14.509,
    "poster_path": "/70aurzbqFMuJnwhIVW2aXeyzBAp.jpg",
    "release_date": "2007-10-12",
    "title": "Twitches Too",
    "video": false,
    "vote_average": 6.771,
    "vote_count": 325
  },
  {
    "adult": false,
    "backdrop_path": "/1qSo3zT9XAQYcbZaLBn46mTeTHZ.jpg",
    "genre_ids": [
      878,
      9648,
      18,
      53,
      10770
    ],
    "id": 569547,
    "original_language": "en",
    "original_title": "Black Mirror: Bandersnatch",
    "overview": "In 1984, a young programmer begins to question reality as he adapts a dark fantasy novel into a video game. A mind-bending tale with multiple endings.",
    "popularity": 17.276,
    "poster_path": "/fR0VZ0VE598zl1lrYf7IfBqEwQ2.jpg",
    "release_date": "2018-12-28",
    "title": "Black Mirror: Bandersnatch",
    "video": false,
    "vote_average": 6.767,
    "vote_count": 3714
  },
  {
    "adult": false,
    "backdrop_path": "/vBBI4eAc9Hs344kko5eqPZTajLl.jpg",
    "genre_ids": [
      10770,
      10751,
      35,
      14
    ],
    "id": 325189,
    "original_language": "en",
    "original_title": "Teen Beach 2",
    "overview": "When characters from the movie musical “Wet Side Story” get stuck in the real world, teens Brady and Mack must find a way to return them home.",
    "popularity": 16.247,
    "poster_path": "/fa7kzaraZaCVO559kp7yMASACCF.jpg",
    "release_date": "2015-06-26",
    "title": "Teen Beach 2",
    "video": false,
    "vote_average": 6.764,
    "vote_count": 560
  },
  {
    "adult": false,
    "backdrop_path": "/jbYJbHBsCtcewKM68YIyIzjvdhP.jpg",
    "genre_ids": [
      16,
      35,
      878,
      10770
    ],
    "id": 278427,
    "original_language": "en",
    "original_title": "Family Guy Presents: It's a Trap!",
    "overview": "With the Griffins stuck again at home during a blackout, Peter tells the story of “Star Wars Episode VI: Return of the Jedi.”",
    "popularity": 12.816,
    "poster_path": "/nGER5w4H3g2ujD8Zodxn0WXk1l4.jpg",
    "release_date": "2010-12-21",
    "title": "Family Guy Presents: It's a Trap!",
    "video": false,
    "vote_average": 6.756,
    "vote_count": 399
  },
  {
    "adult": false,
    "backdrop_path": "/biWonOe1GrPEMqvXhr7FbLox6xt.jpg",
    "genre_ids": [
      35,
      18,
      10751,
      14,
      10770
    ],
    "id": 21481,
    "original_language": "en",
    "original_title": "Twitches",
    "overview": "Twins separated at birth, Camryn and Alex meet by chance for the first time on their 21st birthday and discover they're witches with the power to save their homeland of Coventry from the evil that threatens it. But when Camryn leaves Alex to face the darkness alone, will Coventry be doomed? Or will the sisters multiply their magic by standing together?",
    "popularity": 14.611,
    "poster_path": "/oQ2wWWefU2flwuPgdIkLGhPq6Tk.jpg",
    "release_date": "2005-10-14",
    "title": "Twitches",
    "video": false,
    "vote_average": 6.746,
    "vote_count": 482
  },
  {
    "adult": false,
    "backdrop_path": "/sYbdAWcTqcdLtpAnwIWjrIw6t0r.jpg",
    "genre_ids": [
      10751,
      10770,
      16
    ],
    "id": 359983,
    "original_language": "en",
    "original_title": "The Lion Guard: Return of the Roar",
    "overview": "Set in the African savannah, the film follows Kion as he assembles the members of the 'Lion Guard'. Throughout the film, the diverse team of young animals will learn how to utilize each of their unique abilities to solve problems and accomplish tasks to maintain balance within the Circle of Life, while also introducing viewers to the vast array of animals that populate the prodigious African landscape.",
    "popularity": 19.593,
    "poster_path": "/duqg6CiSik02nSXjiQHo8TcwY4b.jpg",
    "release_date": "2015-11-22",
    "title": "The Lion Guard: Return of the Roar",
    "video": false,
    "vote_average": 6.703,
    "vote_count": 1214
  },
  {
    "adult": false,
    "backdrop_path": "/AfBGTLp9JtsWNUJC6rP1U1XCPCE.jpg",
    "genre_ids": [
      878,
      18,
      10770
    ],
    "id": 7012,
    "original_language": "en",
    "original_title": "The Day After",
    "overview": "In the mid-1980s, the U.S. is poised on the brink of nuclear war. This shadow looms over the residents of a small town in Kansas as they continue their daily lives. Dr. Russell Oakes maintains his busy schedule at the hospital, Denise Dahlberg prepares for her upcoming wedding, and Stephen Klein is deep in his graduate studies. When the unthinkable happens and the bombs come down, the town's residents are thrust into the horrors of nuclear winter.",
    "popularity": 18.116,
    "poster_path": "/6ZISRUN27tpAEstCuGRKsH7Wwxe.jpg",
    "release_date": "1983-11-20",
    "title": "The Day After",
    "video": false,
    "vote_average": 6.691,
    "vote_count": 356
  },
  {
    "adult": false,
    "backdrop_path": "/5EFATeYsjwo6Hjud91JEpy8SK4G.jpg",
    "genre_ids": [
      10770,
      14,
      10751,
      35
    ],
    "id": 15674,
    "original_language": "en",
    "original_title": "Sabrina the Teenage Witch",
    "overview": "A girl, sent by her parents to live with her two eccentric aunts, finds out on her sixteenth birthday that she is a witch.",
    "popularity": 9.817,
    "poster_path": "/mpWf9g1B1PGhoatOBcC5r9RglEM.jpg",
    "release_date": "1996-04-07",
    "title": "Sabrina the Teenage Witch",
    "video": false,
    "vote_average": 6.69,
    "vote_count": 308
  },
  {
    "adult": false,
    "backdrop_path": "/rQavRvcXYbv2gRAYhIEwV3gDpyX.jpg",
    "genre_ids": [
      10751,
      14,
      35,
      10770,
      28
    ],
    "id": 34204,
    "original_language": "en",
    "original_title": "Return to Halloweentown",
    "overview": "As Halloweentown prepares to celebrate its 1,000th anniversary, Marnie Piper and her brother Dylan return to Witch University, where trouble is in session from the Sinister Sisters and from someone who's plotting to use Marnie's powers for evil.",
    "popularity": 13.009,
    "poster_path": "/yYIVsEUyGdp8bEtRjOZGwQA3qmq.jpg",
    "release_date": "2006-10-20",
    "title": "Return to Halloweentown",
    "video": false,
    "vote_average": 6.688,
    "vote_count": 582
  },
  {
    "adult": false,
    "backdrop_path": "/3SXATaC4JZA8qxLyAUFjcq17BBV.jpg",
    "genre_ids": [
      10770,
      35,
      10751,
      18
    ],
    "id": 81440,
    "original_language": "en",
    "original_title": "Good Luck Charlie, It's Christmas!",
    "overview": "Teddy Duncan's middle-class family embarks on a road trip from their home in Denver to visit Mrs. Duncans Parents, the Blankenhoopers, in Palm Springs. When they find themselves stranded between Denver and Utah, they try to hitch a ride to Las Vegas with a seemingly normal older couple in a station wagon from Roswell, New Mexico. It turns out that the couple believes they are the victims of alien abduction. The Duncan's must resort to purchasing a clunker Yugo to get to Utah, have their luggage stolen in Las Vegas, and survive a zany Christmas with Grandpa and Grandma Blankenhooper.",
    "popularity": 23.329,
    "poster_path": "/ecuJMYZM3HQ96mnWtmyXoHb7s7T.jpg",
    "release_date": "2011-12-02",
    "title": "Good Luck Charlie, It's Christmas!",
    "video": false,
    "vote_average": 6.687,
    "vote_count": 398
  },
  {
    "adult": false,
    "backdrop_path": "/dqtosyPcgnotoMuo8wy4xwY1Bxe.jpg",
    "genre_ids": [
      80,
      18,
      36,
      53,
      10770
    ],
    "id": 363992,
    "original_language": "en",
    "original_title": "The Wizard of Lies",
    "overview": "A look behind the scenes at Bernie Madoff's massive Ponzi scheme, how it was perpetrated on the public and the trail of destruction it left in its wake, both for the victims and Madoff's family.",
    "popularity": 18.778,
    "poster_path": "/8k4lJ4e0hvDQtKpItXmmPdw69sO.jpg",
    "release_date": "2017-05-11",
    "title": "The Wizard of Lies",
    "video": false,
    "vote_average": 6.658,
    "vote_count": 531
  },
  {
    "adult": false,
    "backdrop_path": "/5btPLADkUW3gxzIs25VdqRAOMtB.jpg",
    "genre_ids": [
      35,
      18,
      10751,
      10770
    ],
    "id": 81250,
    "original_language": "en",
    "original_title": "Geek Charming",
    "overview": "Film geek Josh is looking for the subject of his new documentary when a chance meeting puts the perfect star in his sights—Dylan, his school's most popular junior. But Dylan's hopes of using the film to become Blossom Queen don't quite match with Josh's goal to make a hard-hitting exposé about popularity. Will Josh shoot the film as planned, or show Dylan as the truly interesting person she is?",
    "popularity": 16.998,
    "poster_path": "/xweQBQSYQyHKiUxN1nCDQbLvJE0.jpg",
    "release_date": "2011-11-11",
    "title": "Geek Charming",
    "video": false,
    "vote_average": 6.6,
    "vote_count": 730
  },
  {
    "adult": false,
    "backdrop_path": "/rf0QbNm135ZHRZzUf7djUPm2pFw.jpg",
    "genre_ids": [
      10751,
      10770,
      35
    ],
    "id": 19458,
    "original_language": "en",
    "original_title": "Princess Protection Program",
    "overview": "When her nation is invaded, a young princess is taken into the Princess Protection Program. She is relocated to Louisiana, where she stays with a covert agent and his tomboyish daughter, and must learn how to behave like an ordinary teenager.",
    "popularity": 27.553,
    "poster_path": "/aKs0ufPp0agLptnhEutDOlfwfdH.jpg",
    "release_date": "2010-02-13",
    "title": "Princess Protection Program",
    "video": false,
    "vote_average": 6.638,
    "vote_count": 1635
  },
  {
    "adult": false,
    "backdrop_path": "/mQUNXRA6uaf4kS1mUUoDKk4qaDB.jpg",
    "genre_ids": [
      18,
      9648,
      53,
      10770
    ],
    "id": 236399,
    "original_language": "en",
    "original_title": "Flowers in the Attic",
    "overview": "After the sudden death of their father, four children face cruel treatment from their ruthless grandmother.",
    "popularity": 17.833,
    "poster_path": "/owzDkkxL2DogC2mq1fgIvrlDcux.jpg",
    "release_date": "2014-01-18",
    "title": "Flowers in the Attic",
    "video": false,
    "vote_average": 6.631,
    "vote_count": 337
  },
  {
    "adult": false,
    "backdrop_path": "/7jKVrSLqPxOynC9z5gel4BNmhui.jpg",
    "genre_ids": [
      10751,
      10770,
      12,
      35,
      18,
      14,
      28
    ],
    "id": 26736,
    "original_language": "en",
    "original_title": "Wizards of Waverly Place: The Movie",
    "overview": "A young wizard accidentally conjures a spell that puts her family in jeopardy.",
    "popularity": 16.292,
    "poster_path": "/reHGWHlF5tHwFQiFmsWHn9gwIpq.jpg",
    "release_date": "2009-08-28",
    "title": "Wizards of Waverly Place: The Movie",
    "video": false,
    "vote_average": 6.625,
    "vote_count": 1344
  },
  {
    "adult": false,
    "backdrop_path": "/mNjoA9jDNbxPJqeYmeETLStpYZF.jpg",
    "genre_ids": [
      10749,
      10770
    ],
    "id": 483104,
    "original_language": "en",
    "original_title": "A Christmas Prince",
    "overview": "When a reporter goes undercover as a nanny to get the inside scoop on a playboy prince, she gets tangled in some royal intrigue and ends up finding love - but will she be able to keep up her lie?",
    "popularity": 10.491,
    "poster_path": "/x0IGQsMzVbsF7noj5cCfEk1GU7s.jpg",
    "release_date": "2017-11-17",
    "title": "A Christmas Prince",
    "video": false,
    "vote_average": 6.621,
    "vote_count": 1390
  },
  {
    "adult": false,
    "backdrop_path": "/2p1nyBVSEBiCTrrZeVSV9nIsqHr.jpg",
    "genre_ids": [
      35,
      18,
      10751,
      10402,
      10749,
      10770
    ],
    "id": 10947,
    "original_language": "en",
    "original_title": "High School Musical",
    "overview": "Troy, the popular captain of the basketball team, and Gabriella, the brainy and beautiful member of the academic club, break all the rules of East High society when they secretly audition for the leads in the school's musical. As they reach for the stars and follow their dreams, everyone learns about acceptance, teamwork, and being yourself.",
    "popularity": 21.828,
    "poster_path": "/bg1eLo2OjySRYKaTO89ZDsqUcJ4.jpg",
    "release_date": "2006-01-20",
    "title": "High School Musical",
    "video": false,
    "vote_average": 6.569,
    "vote_count": 4398
  },
  {
    "adult": false,
    "backdrop_path": "/aS7M839gMmcokvUwNM3DFqOLqzu.jpg",
    "genre_ids": [
      35,
      18,
      10751,
      10402,
      10749,
      10770
    ],
    "id": 13649,
    "original_language": "en",
    "original_title": "High School Musical 2",
    "overview": "The East High Wildcats are gearing up for big fun as they land the coolest summer jobs imaginable. Troy, Gabriella, Chad, and Taylor have scored sweet gigs at the Lava Springs Country Club owned by Sharpay and Ryan's family. Sharpay's first rule of business: Get Troy. As Troy experiences a life of privilege he's never known, will he give up the Wildcats and Gabriella to rise to the top?",
    "popularity": 19.321,
    "poster_path": "/la2kiVWDm2vuB4APZDgCCmuBh4K.jpg",
    "release_date": "2007-08-17",
    "title": "High School Musical 2",
    "video": false,
    "vote_average": 6.529,
    "vote_count": 3583
  },
  {
    "adult": false,
    "backdrop_path": "/zUCagf1HijkgQnaI2opuJZquQbR.jpg",
    "genre_ids": [
      10770,
      35
    ],
    "id": 287689,
    "original_language": "en",
    "original_title": "7 Days in Hell",
    "overview": "A fictional documentary-style expose on the rivalry between two tennis stars who battled it out in a 1999 match that lasted seven days.",
    "popularity": 13.941,
    "poster_path": "/fyY19vwlKaJfPJHunvc7fjQczI1.jpg",
    "release_date": "2015-07-11",
    "title": "7 Days in Hell",
    "video": false,
    "vote_average": 6.483,
    "vote_count": 349
  },
  {
    "adult": false,
    "backdrop_path": "/7VSh4KRB38gs4t4Dlub8GwXNUub.jpg",
    "genre_ids": [
      18,
      12,
      10749,
      10770
    ],
    "id": 115290,
    "original_language": "en",
    "original_title": "Blue Lagoon: The Awakening",
    "overview": "Two high school students become stranded on a tropical island and must rely on each other for survival. They learn more about themselves and each other while falling in love.",
    "popularity": 37.821,
    "poster_path": "/ptsBY9Aqo4Mn0V1krI5s8WfFxzW.jpg",
    "release_date": "2012-06-16",
    "title": "Blue Lagoon: The Awakening",
    "video": false,
    "vote_average": 6.459,
    "vote_count": 1341
  },
  {
    "adult": false,
    "backdrop_path": "/oIreZi8CKwLTFF1dYKSUEjVsje1.jpg",
    "genre_ids": [
      16,
      10751,
      10770
    ],
    "id": 79218,
    "original_language": "en",
    "original_title": "Ice Age: A Mammoth Christmas",
    "overview": "When Sid accidentally destroys Manny's heirloom Christmas rock and ends up on Santa's naughty list, he leads a hilarious quest to the North Pole to make things right and ends up making things much worse. Now it's up to Manny and his prehistoric posse to band together and save Christmas for the entire world!",
    "popularity": 28.624,
    "poster_path": "/ue5417HaDcvgMDusryenwwwZARq.jpg",
    "release_date": "2011-11-24",
    "title": "Ice Age: A Mammoth Christmas",
    "video": false,
    "vote_average": 6.4,
    "vote_count": 608
  },
  {
    "adult": false,
    "backdrop_path": "/q9ZLjqti3UTt5ZC3qQMZhRNueGc.jpg",
    "genre_ids": [
      35,
      10751,
      10749,
      10770
    ],
    "id": 738646,
    "original_language": "en",
    "original_title": "Operation Christmas Drop",
    "overview": "While gathering evidence to support closing a tropical U.S. Air Force base, a congressional aide warms to its generous captain.",
    "popularity": 15.991,
    "poster_path": "/1fUcKFDy58DhWYd5Y7Nu5DgpxaE.jpg",
    "release_date": "2020-11-05",
    "title": "Operation Christmas Drop",
    "video": false,
    "vote_average": 6.439,
    "vote_count": 515
  },
  {
    "adult": false,
    "backdrop_path": "/dbjyGc3pd02FJ9vkGj1MPGLqFOq.jpg",
    "genre_ids": [
      10751,
      10402,
      35,
      18,
      10770,
      10749
    ],
    "id": 13655,
    "original_language": "en",
    "original_title": "Camp Rock",
    "overview": "When Mitchie gets a chance to attend Camp Rock, her life takes an unpredictable twist, and she learns just how important it is to be true to yourself.",
    "popularity": 14.912,
    "poster_path": "/7IXMqZnwccogptThay3togKIFWw.jpg",
    "release_date": "2008-06-20",
    "title": "Camp Rock",
    "video": false,
    "vote_average": 6.418,
    "vote_count": 2020
  },
  {
    "adult": false,
    "backdrop_path": "/vt5UhqjyWYbmJdZhrQsWpRCqCra.jpg",
    "genre_ids": [
      10751,
      878,
      10770
    ],
    "id": 286987,
    "original_language": "en",
    "original_title": "How to Build a Better Boy",
    "overview": "After inadvertently inputting the qualities of the ideal boyfriend into a high-tech government computer, two social outcasts named Mae and Gabby must contend with Albert, a cybernetic sweetheart with only objective: to treat Mae to the perfect highschool romance.",
    "popularity": 9.439,
    "poster_path": "/ivo09vYN76w3epqAv9jS9BEXi5N.jpg",
    "release_date": "2014-11-18",
    "title": "How to Build a Better Boy",
    "video": false,
    "vote_average": 6.4,
    "vote_count": 380
  },
  {
    "adult": false,
    "backdrop_path": "/uC0F3e3thSjuCLvu0ELCNRVuf7a.jpg",
    "genre_ids": [
      12,
      16,
      35,
      10751,
      10770
    ],
    "id": 387893,
    "original_language": "en",
    "original_title": "Ice Age: The Great Egg-Scapade",
    "overview": "A harried prehistoric bird mother entrusts her precious, soon-to-hatch egg to Sid. When she recommends him to her neighbours, business booms at his new egg-sitting service. However, dastardly pirate bunny, Squint, who is seeking revenge on the herd, steals, camouflages and hides all the eggs. Once again, with Squint’s twin brother assisting, Manny, Diego and the rest of the gang come to the rescue and take off on a daring mission that turns into the world’s first Easter egg hunt.",
    "popularity": 31.393,
    "poster_path": "/ysQqYp9G37Q114Nc6uvCHbDmaj6.jpg",
    "release_date": "2016-03-19",
    "title": "Ice Age: The Great Egg-Scapade",
    "video": false,
    "vote_average": 6.375,
    "vote_count": 441
  },
  {
    "adult": false,
    "backdrop_path": "/6BhqBYXQvlIOgGfkhF4aR3tTRW.jpg",
    "genre_ids": [
      16,
      18,
      10749,
      10770
    ],
    "id": 21057,
    "original_language": "ja",
    "original_title": "海がきこえる",
    "overview": "At Kichijōji Station, Tokyo, Taku Morisaki glimpses a familiar woman on the platform opposite boarding a train. Later, her photo falls from a shelf as he exits his apartment before flying to Kōchi Prefecture. Picking it up, he looks at it briefly before leaving. As the aeroplane takes off, he narrates the events that brought her into his life...",
    "popularity": 26.05,
    "poster_path": "/fSR1LLMIJZ6WcQEkM82yKy4F9vQ.jpg",
    "release_date": "1994-10-07",
    "title": "Ocean Waves",
    "video": false,
    "vote_average": 6.363,
    "vote_count": 786
  },
  {
    "adult": false,
    "backdrop_path": "/6LX5mBtaYQwz66qCqWJiYi8fCYb.jpg",
    "genre_ids": [
      35,
      10402,
      10770
    ],
    "id": 44244,
    "original_language": "en",
    "original_title": "Camp Rock 2: The Final Jam",
    "overview": "Mitchie can't wait to go back to Camp Rock and spend the summer making new music with her friends and superstar Shane Gray. But the slick new camp across the lake, Camp Star, has drummed up some serious competition – featuring newcomers Luke and Dana. In a sensational battle of the bands, with Camp Rock's future at stake, will Camp Star's flashy production and over-the-top antics win out, or will Camp Rockers prove that music, teamwork, and spirit are what truly matter?",
    "popularity": 14.324,
    "poster_path": "/8RSdWqC259zR72Jjo6ANAM4ndhM.jpg",
    "release_date": "2010-09-17",
    "title": "Camp Rock 2: The Final Jam",
    "video": false,
    "vote_average": 6.331,
    "vote_count": 1464
  },
  {
    "adult": false,
    "backdrop_path": "/98MW3zxRdBzlnyLpAQvMdY0pe6G.jpg",
    "genre_ids": [
      10751,
      35,
      18,
      10402,
      10770
    ],
    "id": 37609,
    "original_language": "en",
    "original_title": "The Cheetah Girls 2",
    "overview": "Best friends Galleria, Chanel, Dorinda, and Aqua, A.K.A. the girl band \"The Cheetahs,\" get the opportunity of a lifetime when they strut their way to Barcelona, Spain, to perform in an international music festival. Along the way, the \"amigas Cheetahs\" learn that, although their paths are not the same, they are lucky to have one another for the journey.",
    "popularity": 10.771,
    "poster_path": "/vhcqsTbxLRwHiQpJq3ADJg9Er5P.jpg",
    "release_date": "2006-07-31",
    "title": "The Cheetah Girls 2",
    "video": false,
    "vote_average": 6.258,
    "vote_count": 388
  },
  {
    "adult": false,
    "backdrop_path": "/2BqRBUCvtq38d9sfP7s0D69PHfh.jpg",
    "genre_ids": [
      10770,
      10751,
      35,
      14
    ],
    "id": 36968,
    "original_language": "en",
    "original_title": "Life-Size",
    "overview": "Sad and lonely after the death of her mother, Casey would do anything to see her again. But when a series of mystic mishaps mistakenly brings her fashion doll “Eve” to life instead, it changes Casey’s world forever!",
    "popularity": 15.134,
    "poster_path": "/wZr8uruU3Z4A1GsFd79L4cRbu7h.jpg",
    "release_date": "2000-03-05",
    "title": "Life-Size",
    "video": false,
    "vote_average": 6.208,
    "vote_count": 361
  },
  {
    "adult": false,
    "backdrop_path": "/m57sjSxbsPt1Y9H5IjujsMdsBmK.jpg",
    "genre_ids": [
      10751,
      10770,
      35
    ],
    "id": 14008,
    "original_language": "en",
    "original_title": "Cadet Kelly",
    "overview": "Hyperactive teenager Kelly is enrolled into a military school when her new stepfather becomes the Commandant. At first she has problems fitting in and taking orders until she tries out for the drill team.",
    "popularity": 16.106,
    "poster_path": "/eKtznndgJoVG9S9UENc7kHqmhgM.jpg",
    "release_date": "2002-03-07",
    "title": "Cadet Kelly",
    "video": false,
    "vote_average": 6.201,
    "vote_count": 561
  },
  {
    "adult": false,
    "backdrop_path": "/agnO4yvC1H05nEbqonBZ5TH7EcE.jpg",
    "genre_ids": [
      14,
      10751,
      18,
      10770
    ],
    "id": 50479,
    "original_language": "en",
    "original_title": "Avalon High",
    "overview": "Disney Channel's production of Julie Sherman Wolfe's screenplay adaptation of the popular novel Avalon High by Meg Cabot. Elaine \"Ellie\" Harrison has just moved from Minnesota to Annapolis, Maryland while her parents take a year long sabbatical to continue their medieval studies in nearby DC. Her new high school, Avalon High, seems like a typical high school with the stereotypical students: Lance the jock, Jennifer the cheerleader, Marco, the bad boy/desperado, and Will, the senior class president, quarterback, and all around good guy. But not everyone at Avalon High is who they appear to be, not even Ellie herself. Eventually, it becomes apparent that Avalon High is a situation where the ancient Arthurian legend is repeating itself. Will, Jennifer, Lance, Marco, and Mr. Morton all correspond to King Arthur, Queen Guinevere, Knight Lancelot, Mordred, and Merlin, respectively.",
    "popularity": 10.55,
    "poster_path": "/hgS7dPj4e6IYzDXn5IHA6XIbKfl.jpg",
    "release_date": "2011-01-28",
    "title": "Avalon High",
    "video": false,
    "vote_average": 6.193,
    "vote_count": 531
  },
  {
    "adult": false,
    "backdrop_path": "/fq1wk9qCcP5HUrkPh579gIlISWX.jpg",
    "genre_ids": [
      35,
      18,
      10751,
      10770,
      10402
    ],
    "id": 89185,
    "original_language": "en",
    "original_title": "Radio Rebel",
    "overview": "High school senior Tara is so painfully shy that she dreads speaking to anyone in the hallways or getting called on in class. But in the privacy of her bedroom with her iPod in hand, she rocks out -- doing mock broadcasts for Miami's hottest FM radio station, which happens to be owned by her stepfather. When a slot opens up at The SLAM, Tara surprises herself by blossoming behind the mike into confident, \"Radio Rebel\" -- and to everyone's shock, she's a hit!",
    "popularity": 20.363,
    "poster_path": "/wycDdx2BrdNKlyTZoZT8uLeu6dq.jpg",
    "release_date": "2012-06-09",
    "title": "Radio Rebel",
    "video": false,
    "vote_average": 6.2,
    "vote_count": 798
  },
  {
    "adult": false,
    "backdrop_path": "/kuXldgiMg0YZMD8XV4n2orFa1FX.jpg",
    "genre_ids": [
      10751,
      28,
      12,
      10770
    ],
    "id": 61717,
    "original_language": "en",
    "original_title": "Wendy Wu: Homecoming Warrior",
    "overview": "It is the story of an average, popular American teenager named Wendy Wu who discovers that in order to win the coveted crown she must first learn the way of the warrior. Wendy Wu has a one track mind, and that track leads directly to the title of homecoming queen -- no unscheduled stops, and no unnecessary detours. When a mysterious Chinese monk named Shen arrives to mold Wendy into a fearless kung fu warrior, however, her royal aspirations suddenly jump the track as she desperately attempts to juggle her boyfriend, her homework, and of course, the fierce competition to become homecoming queen. Now, as Wendy begins to train her mind, body, and spirit in the ancient tradition of the martial arts and her inner warrior gradually begins to emerge, the girl who once obsessed over popularity finally begins to put that popularity into perspective as she gradually realizes what truly matters in life.",
    "popularity": 15.776,
    "poster_path": "/6EfY13SHzvpwXg2KPixnbCXuUoR.jpg",
    "release_date": "2006-06-16",
    "title": "Wendy Wu: Homecoming Warrior",
    "video": false,
    "vote_average": 6.156,
    "vote_count": 403
  },
  {
    "adult": false,
    "backdrop_path": "/s7tRhQ8oDJSdsy3YvDp04KtK9nC.jpg",
    "genre_ids": [
      10770,
      35,
      10751
    ],
    "id": 278774,
    "original_language": "en",
    "original_title": "Zapped",
    "overview": "Zoey is a talented dancer whose organized life is rudely disrupted when she moves in with her new step-dad and three step-brothers, until she discovers a dog-training app that can get boys to obey her every command. But she soon learns that it isn't the cure-all she had hoped for.",
    "popularity": 14.773,
    "poster_path": "/u33QFfbvChD5LNcuZD0LsSVnoa1.jpg",
    "release_date": "2014-06-27",
    "title": "Zapped",
    "video": false,
    "vote_average": 6.138,
    "vote_count": 585
  },
  {
    "adult": false,
    "backdrop_path": "/socMWFFL8f5j41tVQ9TO64QkSxB.jpg",
    "genre_ids": [
      10751,
      35,
      18,
      10402,
      10770
    ],
    "id": 27621,
    "original_language": "en",
    "original_title": "The Cheetah Girls: One World",
    "overview": "Chanel, Dorinda, and Aqua are off to India to star in a Bollywood movie. But when they discover that they will have to compete against each other to get the role in the movie, will the Cheetahs break up again?",
    "popularity": 11.614,
    "poster_path": "/aIxBQvA3h6WbD3LJtXspWL8GOw3.jpg",
    "release_date": "2008-08-22",
    "title": "The Cheetah Girls: One World",
    "video": false,
    "vote_average": 6.1,
    "vote_count": 314
  },
  {
    "adult": false,
    "backdrop_path": "/8z5qtVE2N3AuA3bmvIQsI10Wjg8.jpg",
    "genre_ids": [
      27,
      18,
      10770
    ],
    "id": 7342,
    "original_language": "en",
    "original_title": "Carrie",
    "overview": "Carrie White is a lonely and painfully shy teenage girl with telekinetic powers who is slowly pushed to the edge of insanity by frequent bullying from both classmates at her school, and her own religious, but abusive, mother.",
    "popularity": 15.301,
    "poster_path": "/knjeEeeyIwDkUtZwDfJOcUIuNdB.jpg",
    "release_date": "2002-11-04",
    "title": "Carrie",
    "video": false,
    "vote_average": 6.061,
    "vote_count": 445
  },
  {
    "adult": false,
    "backdrop_path": "/qJVUx5xUes9cTDpMiNWx4Fab2ac.jpg",
    "genre_ids": [
      10751,
      35,
      18,
      10402,
      10770
    ],
    "id": 32293,
    "original_language": "en",
    "original_title": "The Cheetah Girls",
    "overview": "A four-member teen girl group named the Cheetah Girls go to a Manhattan High School for the Performing Arts and try to become the first freshmen to win the talent show in the school's history. During the talent show auditions, they meet a big-time producer named Jackal Johnson, who tries to make the group into superstars, but the girls run into many problems.",
    "popularity": 9.122,
    "poster_path": "/2n813ySvmLdGV1CohEne7nAjUd2.jpg",
    "release_date": "2003-08-15",
    "title": "The Cheetah Girls",
    "video": false,
    "vote_average": 6,
    "vote_count": 452
  },
  {
    "adult": false,
    "backdrop_path": "/uttOGgMYQJqwxL6OohWHFk6rpW7.jpg",
    "genre_ids": [
      10751,
      14,
      35,
      10770
    ],
    "id": 39345,
    "original_language": "en",
    "original_title": "Casper Meets Wendy",
    "overview": "When a warlock threatens Wendy the Good Little Witch, she and her aunts hide out at a resort where Casper the Ghost is vacationing with his uncles. Although Casper and Wendy are told ghosts and witches don't get along, the two are kindred spirits! This spooky family-friendly adventure finds Casper and Wendy bridging the ghost-witch divide to battle the warlock who is intent on destroying Wendy.",
    "popularity": 16.41,
    "poster_path": "/zYJWQvee9CN6nc9En2KUWewHGHr.jpg",
    "release_date": "1998-09-08",
    "title": "Casper Meets Wendy",
    "video": false,
    "vote_average": 6,
    "vote_count": 364
  },
  {
    "adult": false,
    "backdrop_path": "/c6UZKwtnuwMEWcQzyrT9lXsyVXj.jpg",
    "genre_ids": [
      12,
      10751,
      14,
      878,
      10770
    ],
    "id": 1884,
    "original_language": "en",
    "original_title": "The Ewok Adventure",
    "overview": "Wicket the Ewok and his friends agree to help two shipwrecked human children, Mace and Cindel, on a quest to find their parents.",
    "popularity": 13.362,
    "poster_path": "/4GrECLKaJhYA6ooSTOG0XEuPnSl.jpg",
    "release_date": "1984-11-25",
    "title": "The Ewok Adventure",
    "video": false,
    "vote_average": 5.903,
    "vote_count": 331
  },
  {
    "adult": false,
    "backdrop_path": "/m0uy78mSoSqh470bGJuOHGiEZnQ.jpg",
    "genre_ids": [
      10749,
      35,
      10770
    ],
    "id": 39285,
    "original_language": "en",
    "original_title": "Beauty & the Briefcase",
    "overview": "A freelance writer looking for romance sells a story to Cosmopolitan magazine about finding love in the workplace and goes undercover at a Finance Company.",
    "popularity": 11.057,
    "poster_path": "/zN9FYOXf5tUYjgget7yOzu8TlZU.jpg",
    "release_date": "2010-07-20",
    "title": "Beauty & the Briefcase",
    "video": false,
    "vote_average": 5.9,
    "vote_count": 399
  },
  {
    "adult": false,
    "backdrop_path": "/ikL5OZJxQv4Fe4gpDbjYlqAwcGN.jpg",
    "genre_ids": [
      18,
      10751,
      10770,
      35
    ],
    "id": 84105,
    "original_language": "en",
    "original_title": "Frenemies",
    "overview": "Zendaya and Bella Thorne, who play Rocky and CeCe in hit Disney Channel series Shake It Up, star in this Disney Channel Original Movie. Three pairs of friends relationships go from good to bad and back again. Several couple fall out over girls, boys and work. Can all these couples settle their differences and be friends again?",
    "popularity": 16.094,
    "poster_path": "/cfEUQG5Jv5SHVgq6pPfybS57ORO.jpg",
    "release_date": "2012-01-13",
    "title": "Frenemies",
    "video": false,
    "vote_average": 5.8,
    "vote_count": 418
  },
  {
    "adult": false,
    "backdrop_path": "/6jR6IZkX7USdRsAzoq7BTqKFgqP.jpg",
    "genre_ids": [
      12,
      10770
    ],
    "id": 231474,
    "original_language": "en",
    "original_title": "The Hunters",
    "overview": "Imagine if all mythical artifacts, from Jason's Golden Fleece to Cinderella's glass slippers, were real. Well, they are -- and for centuries, a secret society called the Hunters has been sworn to protect them from an evil force called the Krugen.",
    "popularity": 8.644,
    "poster_path": "/ubR6x50z4aLflgzJcw7X7HflKKr.jpg",
    "release_date": "2013-10-25",
    "title": "The Hunters",
    "video": false,
    "vote_average": 5.631,
    "vote_count": 335
  },
  {
    "adult": false,
    "backdrop_path": "/fenaSJdxaMoVYGEFUbi8DFyXOrF.jpg",
    "genre_ids": [
      35,
      10402,
      10770
    ],
    "id": 364067,
    "original_language": "en",
    "original_title": "A Very Murray Christmas",
    "overview": "Bill Murray worries no one will show up to his TV show due to a massive snowstorm in New York City. Through luck and perseverance, guests arrive at Gotham’s Carlyle Hotel to help him — dancing and singing in holiday spirit.",
    "popularity": 11.832,
    "poster_path": "/2ir2DjNNXmMePsyc4inFa8oI23r.jpg",
    "release_date": "2015-12-04",
    "title": "A Very Murray Christmas",
    "video": false,
    "vote_average": 5.255,
    "vote_count": 390
  },
  {
    "adult": false,
    "backdrop_path": "/3mO7fimik20gwkVNXNxbi0RY3wg.jpg",
    "genre_ids": [
      35,
      10751,
      10770
    ],
    "id": 134375,
    "original_language": "en",
    "original_title": "Home Alone: The Holiday Heist",
    "overview": "10-year-old Finn is terrified to learn his family is relocating from sunny California to Maine in the scariest house he has ever seen! Convinced that his new house is haunted, Finn sets up a series of elaborate traps to catch the “ghost” in action. Left home alone with his sister while their parents are stranded across town, Finn’s traps catch a new target – a group of thieves who have targeted Finn’s house.",
    "popularity": 34.037,
    "poster_path": "/6JPrRC0JPM06y17pUXD6w1xMvKi.jpg",
    "release_date": "2012-12-03",
    "title": "Home Alone: The Holiday Heist",
    "video": false,
    "vote_average": 5.23,
    "vote_count": 404
  },
  {
    "adult": false,
    "backdrop_path": "/tV52jYHf2CkFzIMlrn87xs1aPM.jpg",
    "genre_ids": [
      28,
      35,
      878,
      10770,
      27
    ],
    "id": 438970,
    "original_language": "en",
    "original_title": "Sharknado 5: Global Swarming",
    "overview": "Fin and his wife April travel around the world to save their young son who's trapped inside a sharknado.",
    "popularity": 12.443,
    "poster_path": "/jmWFQBtJseHSIloxW20doRCXGgZ.jpg",
    "release_date": "2017-08-06",
    "title": "Sharknado 5: Global Swarming",
    "video": false,
    "vote_average": 4.764,
    "vote_count": 305
  },
  {
    "adult": false,
    "backdrop_path": "/wz9GW2xNzbpfjr3Tc5rKdGuPD49.jpg",
    "genre_ids": [
      28,
      10770,
      878,
      35,
      27
    ],
    "id": 331446,
    "original_language": "en",
    "original_title": "Sharknado 3: Oh Hell No!",
    "overview": "The sharks take bite out of the East Coast when the sharknado hits Washington, D.C. and Orlando, Florida.",
    "popularity": 13.522,
    "poster_path": "/r8qy2CgaSjJYusWy3XkbZieK5aG.jpg",
    "release_date": "2015-07-22",
    "title": "Sharknado 3: Oh Hell No!",
    "video": false,
    "vote_average": 4.626,
    "vote_count": 468
  },
  {
    "adult": false,
    "backdrop_path": "/6gvocf4kU9qJyUVZEDveOtLkaMu.jpg",
    "genre_ids": [
      35,
      10751,
      10770
    ],
    "id": 12536,
    "original_language": "en",
    "original_title": "Home Alone 4",
    "overview": "Kevin McCallister's parents have split up. Now living with his mom, he decides to spend Christmas with his dad at the mansion of his father's rich girlfriend, Natalie. Meanwhile robber Marv Merchants, one of the villains from the first two movies, partners up with a new criminal named Vera to hit Natalie's mansion.",
    "popularity": 45.116,
    "poster_path": "/qRktvMOO2QaCL7gvNyvZDoxPOZj.jpg",
    "release_date": "2002-11-03",
    "title": "Home Alone 4",
    "video": false,
    "vote_average": 4.49,
    "vote_count": 1184
  },
  {
    "adult": false,
    "backdrop_path": "/riGVdQS9gXy38VoSaXXBhmR6A4h.jpg",
    "genre_ids": [
      27,
      35,
      878,
      28,
      10770
    ],
    "id": 205321,
    "original_language": "en",
    "original_title": "Sharknado",
    "overview": "A freak hurricane hits Los Angeles, causing man-eating sharks to be scooped up in tornadoes and flooding the city with shark-infested seawater. Surfer and bar-owner Fin sets out with his friends Baz and Nova to rescue his estranged wife April and teenage daughter Claudia.",
    "popularity": 10.452,
    "poster_path": "/atEmHkVFTSGRYt2PeCiziQqbZnI.jpg",
    "release_date": "2013-07-11",
    "title": "Sharknado",
    "video": false,
    "vote_average": 3.915,
    "vote_count": 1495
  },
  {
    "adult": false,
    "backdrop_path": "/ae9xlnkS2qb5Dy9Mtlu68AWh42O.jpg",
    "genre_ids": [
      14,
      878,
      10751,
      10770
    ],
    "id": 74849,
    "original_language": "en",
    "original_title": "The Star Wars Holiday Special",
    "overview": "Luke Skywalker and Han Solo battle evil Imperial forces to help Chewbacca reach his imperiled family on the Wookiee planet - in time for Life Day, their most important day of the year!",
    "popularity": 14.093,
    "poster_path": "/eRSKviGcTqHd34vCLjcztJF6Eaw.jpg",
    "release_date": "1978-12-01",
    "title": "The Star Wars Holiday Special",
    "video": false,
    "vote_average": 3.343,
    "vote_count": 431
  }
]

// console.log(tvMovie.length)
setTimeout(() => {
  actionGenreBTN = document.getElementById("10770");
  actionGenreBTN.classList.remove("buttonsDisabled")
  actionGenreBTN.classList.add("buttonsEnabled")
  actionGenreBTN.removeAttribute("disabled")
}, 5000)